Alumini/Controllers/askquestionsController.cs
using Alumini.DAL;
using Alumini.MediatorClass;
using Alumini.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Alumini.Controllers
{
    public class askquestionsController : Controller
    {
        AskQuestionDL objDAL = new AskQuestionDL(System.Web.HttpContext.Current.Request.Url.AbsoluteUri);
        utilities objUtil = new utilities(System.Web.HttpContext.Current.Request.Url.AbsoluteUri);
        // GET: askquestions
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult list()
        {
            return View();
        }
        [HttpPost]
        //public ActionResult saveaskquestion(string question_number, string question,string EmpID,string quespublish_totion,string urgency,string description,string mode)
        //{    
        //   // AskQuestionDL obj = new AskQuestionDL();
        //    string xyx=  obj.saveaskquestion(question_number,question,EmpID,quespublish_totion,urgency,description,mode);            
        //    return Content("Question added successfully"); 
        //}


        public JsonResult saveaskquestion(List<AskQuestionModel> lParam)
        {
            AskQuestionModel obj = new AskQuestionModel();
            foreach(var item in lParam)
            {
                obj.question_number = item.question_number;
                obj.mode = item.mode;
                obj.question = item.question;
                obj.description = item.description;
                obj.urgency = item.urgency;
                obj.publish_to = item.publish_to;
                obj.userid = item.userid;  
            }           
            string xyx = objDAL.saveaskquestion(obj);
            return Json(xyx, JsonRequestBehavior.AllowGet);
        }

        public JsonResult savegivenanswer(List<Answer> lAnswer)
        {
            Answer objAnswer = new Answer();
            foreach (var item in lAnswer)
            {
                objAnswer.question_number = item.question_number;
                objAnswer.answer = item.answer;
                objAnswer.answer_given_by = item.answer_given_by;
                objAnswer.question_ask_by = item.question_ask_by;
                objAnswer.question_id = item.question_id;                              
            }
            string answers = objDAL.saveanswers(objAnswer);
            return Json(answers, JsonRequestBehavior.AllowGet);
        }

        
        [HttpPost]
        public JsonResult getaskquestion(string ID, string mode)
        {
            //AskQuestionDL obj = new AskQuestionDL();
            List<AskQuestionModel> Ilist = new List<AskQuestionModel>();
            // Ilist = obj.getaskquestion(ID,mode);
            BusinessLayer obj = new BusinessLayer(new AskQuestionDL(System.Web.HttpContext.Current.Request.Url.AbsoluteUri));
            Ilist = obj.GetData(ID, mode);
            return Json(Ilist, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GenNum()
        {            
            string GUIDnumber = "";
            GUIDnumber = objUtil.GenerateQuestionNumber();
            return Json(GUIDnumber, JsonRequestBehavior.AllowGet);
        }

      public ActionResult  GetQuestionWithReplyAnswer(string ID,string QNum)
        {
            List<AskQuestionModel> Ilist = new List<AskQuestionModel>();
            Ilist = objDAL.GetQuestionWithReplyAnswer(ID,QNum);
            return Json(Ilist, JsonRequestBehavior.AllowGet);
        }
    }
}

Alumini/Views/askquestions/list.cshtml
@Model Alumini.Models.AskQuestionModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    // ViewBag.Title = "list";
}
<script type="text/javascript"
        src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<h2>list</h2>
<script src="~/Scripts/Batchmates/04_ask_questionJs.js"></script>
<input type="hidden" id="hdnEmpID" value="@Session["alumnusid"]" />
<input type="hidden" id="hdnAutoID"  />

<input type="hidden" id="hdnQuestionID"/>
<input type="hidden" id="hdnAskBy"/>
<input type="hidden" id="hdnQuestionNumber"/>
<div class="showMessageClass" style="top: 7.5%; position: fixed; margin-left: 30%; display: block; z-index: 9999;">
    <strong class="AddProductErrorMessage"></strong>
</div>
<div class="content-wrapper">
    <div class="page-content">
        <div class="page-bar">
            <div class="page-title-breadcrumb pt-10">
                <div class="pull-left">
                    <div class="page-title">
                        <span class="icon-question mr-5" style="font-size: 21px;"></span>&nbsp; Questions
                    </div>
                </div>
                <div class="pull-right pr-10">
                    <button type="button" id="btnAskNewQuestion" onclick="clearfields();" class="btn btn-primary btn-animated btn-sm pr-40" data-toggle="modal" data-target="#ask_question">Ask Question<i class="icon-plus3 text-white f-12"></i></button>
                    @*onclick="location.href='@Url.Action("GenNum", "askquestions")'""*@
                </div>
            </div>

            <div class="col-md-12 col-sm-12">
                <div class="borderBox-title tabbable-line">
                    <ul class="nav nav-tabs">
                        <li class="active">
                            <a href="#borderBox_tab1" onclick="GetQuestions('OTHER')" data-toggle="tab">Asked by Other's</a>
                        </li>
                        <li>
                            <a href="#borderBox_tab2" onclick="GetQuestions('BATCHMATE')" data-toggle="tab">Asked by Batch Mates</a>
                        </li>
                        <li>
                            <a href="#borderBox_tab3" onclick="GetQuestions('ME')" data-toggle="tab">Asked by me</a>
                        </li>
                    </ul>
                </div>

                <div class="borderBox-body panel-body card mt-none">
                    <div class="tab-content form-horizontal">
                        <div class="tab-pane active" id="borderBox_tab1">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @* Create Question modal popup author:Mukesh(02-May-2020) *@
    @*@using(Ajax.BeginForm("SaveAskQuestion", "askquestions",new AjaxOptions { UpdateTargetId = "Productresult" }))
        {*@
    <div id="ask_question" class="modal fade in detail-form" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content c-square">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">Add New Question</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-sm-8">
                            <div class="form-group">
                                <label class="control-label">
                                    Question Title <span class="text-danger">*</span>&nbsp;<span id="spnquestion_title" class="text-danger" style="visibility: hidden;">Mandatory field</span>
                                </label>
                                @Html.TextBox("question_title", null, new { @class = "form-control", @placeholder = "add title for your question" })
                                <span class="focus-input"></span>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label class="control-label">
                                    Urgency
                                    <span class="text-danger">*</span>&nbsp;<span id="spnquestion_urgency" class="text-danger" style="visibility: hidden;">Mandatory field</span>
                                </label>
                                @Html.DropDownList("question_urgency", new List<SelectListItem> {
                               new SelectListItem { Text = "- Select -", Value = "1" },
                               new SelectListItem { Text = "Medium", Value = "2" },
                               new SelectListItem { Text = "Normal", Value = "3" },
                               new SelectListItem { Text = "Urgent", Value = "4" }}, new { @class = "form-control input-xs select-search", @validationTabDetails = "validation" })
                                <span class="focus-input"></span>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="control-label">
                                    Who can see?
                                    <span class="text-danger">*</span>&nbsp;<span id="spnpublish_to" class="text-danger" style="visibility: hidden;">Mandatory field</span>
                                </label>
                                @Html.DropDownList("publish_to", new List<SelectListItem> {
                               new SelectListItem { Text = "- Select -", Value = "1" },
                               new SelectListItem { Text = "All", Value = "2" },
                               new SelectListItem { Text = "Only My Batchmates", Value = "3" }}, new { @class = "form-control input-xs select-search", @validationTabDetails = "validation" })
                                <span class="focus-input"></span>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label class="control-label">
                                    Description
                                    <span class="text-danger">*</span>&nbsp;<span id="spnquestion" class="text-danger" style="visibility: hidden;">Mandatory field</span>
                                </label>
                                @Html.TextArea("question", null, new { @class = "form-control", @placeholder = "describe your question", style = "height:130px;" })
                                <span class="focus-input"></span>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="btn-group pull-right">
                                <input type="submit" id="btnSubmit" onclick="return AddNewQuestion();" value="Add" class="btn btn-primary" />
                            </div>
                            <div class="btn-group pull-right mr-5">
                                <input type="button" id="btnSubmit1" value="Delete" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

    <div id="answer_question" class="modal fade in detail-form" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content c-square">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">Answer to the question</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-sm-8">
                            <div class="form-group">
                                <span class="f-16"><b><span id="QuestionNumber"></span>:&nbsp;<span id="QuestionDetail"></span></b></span>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="form-group">
                                <div class="panel">
                                    <form class="detail-form">
                                        <span id="spnAnswerByUser" class="text-danger" style="visibility: hidden;"></span>
                                        <textarea id="AnswerByUser" class="form-control p-text-area" rows="4" placeholder="Answer here"></textarea>
                                    </form>
                                    <footer class="panel-footer">
                                        <button id="AddAnswer" class="AddAnswer btn btn-post pull-right pt-10">Post</button>
                                        <ul class="nav nav-pills"></ul>
                                    </footer>
                                </div>
                                <ul class="bm activity-list allanswers">
                                    @*<li>
                                        <div class="avatar">
                                            <img src="../assets/img/user1.svg" alt="">
                                        </div>
                                        <div class="activity-desk">
                                            <h5>
                                                <a href="#">Mukesh Patil</a> <span>01-Jul-2020 10:40 PM</span>
                                                <a href="#"><span id="AnswerBy"></span></a> <span id="AnswerTime"></span>
                                            </h5>
                                            <p class="text-muted"><b>A20-2:</b> Polymorphism is the ability of an object to take on many forms. The most common use of polymorphism in OOP occurs when a parent class reference is used to refer to a child class object. Any Java object that can pass more than one IS-A test is considered to be polymorphic.</p>
                                        </div>
                                    </li>*@
                                    @*<li>
                                        <div class="avatar">
                                            <img src="../assets/img/user1.svg" alt="">
                                        </div>
                                        <div class="activity-desk">
                                            <h5>
                                                <a href="#">Prashant swami</a> <span>31-Jun-2020 09:09 AM</span>
                                            </h5>
                                            <p class="text-muted"><b>A20-1:</b> Polymorphism means "many forms", and it occurs when we have many classes that are related to each other by inheritance. Like we specified in the previous</p>
                                        </div>
                                    </li>*@
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
</div>