Alumini/Controllers/authenticationController.cs
using Alumini.DAL;
using Alumini.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Alumini.Controllers
{
    public class authenticationController : Controller
    {
        AlumnusRegistration alumnus = new AlumnusRegistration(System.Web.HttpContext.Current.Request.Url.AbsoluteUri);

        // GET: authentication
        public ActionResult login()
        {
            return View();
        }

        public ActionResult register()
        {
            return View();
        }

        public ActionResult users()
        {
            return View();
        }

        [HttpPost]
        public JsonResult SaveRegistration(List<Registration> lParam)
        {
            var returnValue = "";
            foreach (Registration oParam in lParam)
            {
                try
                {
                    returnValue = alumnus.SaveAlumnusRegistration(oParam);
                }
                catch (Exception Ex)
                {
                    throw Ex;
                }
            }
            return Json(returnValue, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult SendEmail(string emailid, string firstname, string lastname)
        {
            string body = string.Empty;
            string result = string.Empty;
            try
            {
                //using streamreader for reading my html template   
                using (StreamReader reader = new StreamReader(Server.MapPath("~/EmailTemplates/Confirmation-Email.html")))
                {
                    body = reader.ReadToEnd();
                }
                body = body.Replace("{firstname}", firstname);
                body = body.Replace("{lastname}", lastname);
                body = body.Replace("{email}", emailid);

                if (Utilities.Utilities.IsEmptyOrNull(emailid))
                {
                    result = Utilities.Utilities.SendEmail(emailid, "[Batchmates]: Verification link", body);
                }

                return Json(result, JsonRequestBehavior.AllowGet);
            }
            catch (Exception Ex)
            {
                throw Ex;
            }
        }

        [HttpPost]
        public ActionResult SignIn(FormCollection oObj)
        {
            Registration oParam = new Registration();
            // Assign the Email and Password to UserLoginForm object
            oParam.email = oObj[0];
            oParam.password = Utilities.Utilities.EncodePassword(oObj[1]);

            // authenticates user with provided email and password in login form
            // author:Mukesh(28-May-2019)
            oParam = alumnus.SignIn(oParam.email, oParam.password);

            if (Utilities.Utilities.IsEmptyOrNull(oParam.alumnus_id))
            {
                Session["alumnusid"] = oParam.alumnus_id;
                Session["first_name"] = oParam.first_name;
                Session["last_name"] = oParam.last_name;
                Session["email"] = oParam.email;

                return RedirectToAction("profile", "batchmates");
            }
            else
            {
                oParam.alert = "Email or Password Incorrect";
                return View("login", oParam);
            }
        }

        [HttpGet]
        public ActionResult VerifyAccount()
        {
            return View();
        }

        [HttpPost]
        public JsonResult VerifyAlumnus(string email)
        {
            string result = alumnus.VerifyAlumnus(email);

            // This function verifies account after user clicks on the link in the email
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

Alumini/Views/authentication/accountverified.cshtml
@{
    ViewBag.Title = "accountverified";
}

<span id="verifyalert"></span>

Alumini/Views/authentication/login.cshtml
<head>
    @{
        ViewBag.Title = "Login";
    }
    @{
        Layout = null;
    }
    <title>Batch Mate - @ViewBag.Title</title>

    <link rel="shortcut icon" href="~/Content/images/favicon.ico" type="image/x-icon" />
    <!-- Fonts-->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300" rel="stylesheet" />
    <!-- Global stylesheets -->
    <link href="~/assets/css/bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/css/responsive.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/css/style.css" rel="stylesheet" type="text/css" />

    <!-- /global stylesheets -->
    <!-- Core JS files -->

    <script type="text/javascript" src="~/Scripts/jquery.min.js"></script>
    <script type="text/javascript" src="~/Scripts/bootstrap.min.js"></script>

    <!-- /core JS files -->

    <script type="text/javascript">
        $(document).ready(function () {
            $('#btnSignIn').click(function () {
                if ($('.login-form input').val() == '') {

                }
                else {
                    $('#btnSignIn').html("<i class='icon-spinner4 spinner position-left'></i> Verifying login data");
                    $('#btnSignIn').addClass('disabled');
                }
            });
            $('#UserName').focus();
        });
    </script>
</head>


<body class="login-container" cz-shortcut-listen="true">
    <div class="page-container">
        <div class="page-content">
            <div class="page-content-wrapper">
                <div class="scrollable" id="scrollable">
                    <div class="login-form" style="top:150px;">
                        @using (Html.BeginForm("signin", "authentication", FormMethod.Post))
                        {
                            <div class="text-center">
                                <img src="~/Content/img/batch-mate-logo.jpg" alt="Batch Mates" height="60">
                            </div>

                            <div class="form-group mt-30">
                                <label>Email</label>
                                @Html.TextBox("uname", null, new { @class = "form-control", @placeholder = "enter your registered email id" })
                                <span class="focus-input"></span>
                            </div>

                            <div class="form-group">
                                <label>Password</label>
                                @Html.TextBox("pass", null, new { @class = "form-control", @type = "password", @placeholder = "*************" })
                                <span class="focus-input"></span>
                            </div>

                            <div class="form-group pull-left">
                                <a href="~/authentication/register" id="btnSignIn" class="btn btn-success btn-md">Click to register</a>
                            </div>

                            <div class="form-group pull-right">
                                <button id="btnSignIn" class="btn btn-primary btn-md" onclick="signin();" type="submit">Sign in</button>
                            </div>
                            <br />
                            <br />
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
<!-- start js include path -->
<script src="../content/js/login.js"></script>
<script src="../content/js/pages.js" type="text/javascript"></script>
<!-- end js include path -->

Alumini/Views/authentication/register.cshtml
@model Alumini.Models.Registration
<head>
    @{
        ViewBag.Title = "Registration";
    }
    @{
        Layout = null;
    }
    <title>Batch Mate - @ViewBag.Title</title>

    <link rel="shortcut icon" href="~/Content/images/favicon.ico" type="image/x-icon" />
    <!-- Fonts-->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300" rel="stylesheet" />
    <!-- icons -->
    <link href="~/assets/js/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Global stylesheets -->
    <link href="~/Content/bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/css/style.css" rel="stylesheet" type="text/css" />

    <!-- /global stylesheets -->
    <!-- Core JS files -->
    <script src="~/assets/js/core/jquery.min.js" type="text/javascript"></script>
    <script src="~/assets/js/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <!-- /core JS files -->

    <script src="~/Scripts/comman_functions.js"></script>
    <script src="~/Scripts/date-custom.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#btnSignIn').click(function () {
                if ($('.login-form input').val() == '') {
                }
                else {
                    $('#btnSignIn').html("<i class='icon-spinner4 spinner position-left'></i> Verifying login data");
                    $('#btnSignIn').addClass('disabled');
                }
            });
            $('#UserName').focus();
        });
    </script>
</head>

@*<form>*@
<div class="container-fluid">
    <div class="navbar navbar-inverse navbar-fixed-top bm-navbar-bg">
        <div class="navbar-header">
            <a class="navbar-brand" href="/authentication/register">
                <img src="../../Content/img/batch-mate-logo.jpg" alt="Klaus Multiparking" width="170px" height="28px" />
            </a>
        </div>
        <div class="navbar-collapse collapse" id="navbar-mobile">
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown dropdown-user">
                    <a class="dropdown-toggle" data-toggle="dropdown">
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <div class="row mt-15">
        <div class="col-md-7 col-sm-7 register-left-box">
            <h4 class="f-22" style="font-weight: normal;">About Batch Mates</h4>
            <p>
                Thanks alumnus for visiting this page. We always wish for your bright career and happy life. You are really an asset for our Institute.
                The purpose behind developing <b>Batch Mates</b> is to guide / support the needy Students / Working professionals / Families etc. who are their in the same city you belong
                and need help in terms of studies, getting jobs, search for shelter and much more other stuff. We hope you will be part of this beautiful idea and surely involve in it.
                We request you to register and join this portal by updating the information. We ensure wihtout your permission your information will not be circulated within the group of people who are part of this portal.
            </p>

            <p>On successful registration you will be able to login this portal. To create an account you should be alumni of the organization. To explore more features of this portal please register.</p>

            <p>Those who are already registered, click the button to go to login page.</p>

            <div class="form-group mt-10">
                <a href="~/authentication/login" id="btnRegister" class="btn btn-success btn-sm">Go to Login Page</a>
            </div>
            <br /><br />
            <p>
                <span style="font-size:11px;">
                    For more information contact on :
                    +91-9960827637 or write an e-mail on <a href="mailto:p_mukesh_s@yahoo.co.in">p_mukesh_s@yahoo.co.in</a>
                </span>
            </p>
        </div>
        <div class="col-md-4 col-sm-4">
            <div class="row">
                <div class="col-sm-11 login-right-box">
                    <div class="form-group mt-10">
                        <h4 style="color:#c71585;">Registration Form</h4>
                        <label>Enter your information</label>
                    </div>
                    <div class="form-group mt-10">
                        <label>First name</label>&nbsp;<span style="color:red">*</span>
                        @Html.TextBoxFor(a => a.first_name, new { @class = "form-control input-xs", @placeholder = "enter first name", @validationTabDetails = "validation" })
                        <span class="focus-input"></span>
                    </div>
                    <div class="form-group mt-10">
                        <label>Last name</label>&nbsp;<span style="color:red">*</span>
                        @Html.TextBoxFor(a => a.last_name, new { @class = "form-control", @placeholder = "enter last name", @validationTabDetails = "validation" })
                        <span class="focus-input"></span>
                    </div>
                    <div class="form-group mt-10">
                        <label>Contact No.</label>&nbsp;<span style="color:red">*</span>
                        @Html.TextBoxFor(a => a.contact_number, new { @class = "form-control", @placeholder = "enter contact no.", @validationTabDetails = "validation" })
                        <span class="focus-input"></span>
                    </div>
                    <div class="form-group mt-10">
                        <label>Batch</label>&nbsp;<span style="color:red">*</span>
                        @*@Html.TextBoxFor(a => a.batch, null, new { @class = "form-control DatepickerCal", @placeholder = "enter batch", @validationTabDetails = "validation" })*@
                        @Html.DropDownList("batch", new List<SelectListItem> {
                            new SelectListItem { Text = "- Select -", Value = "1" },
                            new SelectListItem { Text = "1990", Value = "1990" },
                            new SelectListItem { Text = "1991", Value = "1990" },
                            new SelectListItem { Text = "1992", Value = "1992" },
                  new SelectListItem { Text = "1993", Value = "1993" },
                  new SelectListItem { Text = "1994", Value = "1994" },
                  new SelectListItem { Text = "1995", Value = "1995" },
                  new SelectListItem { Text = "1996", Value = "1996" },
                  new SelectListItem { Text = "1997", Value = "1997" },
                  new SelectListItem { Text = "1998", Value = "1998" },
                  new SelectListItem { Text = "1999", Value = "1999" },
                  new SelectListItem { Text = "2000", Value = "2000" },
                  new SelectListItem { Text = "2001", Value = "2001" },
                  new SelectListItem { Text = "2002", Value = "2002" },
                  new SelectListItem { Text = "2003", Value = "2003" },
                  new SelectListItem { Text = "2004", Value = "2004" },
                  new SelectListItem { Text = "2005", Value = "2005" },
                  new SelectListItem { Text = "2006", Value = "2006" },
                  new SelectListItem { Text = "2007", Value = "2007" },
                  new SelectListItem { Text = "2008", Value = "2008" },
                  new SelectListItem { Text = "2009", Value = "2009" },
                  new SelectListItem { Text = "2010", Value = "2010" },
                  new SelectListItem { Text = "2011", Value = "2011" },
                  new SelectListItem { Text = "2012", Value = "2012" },
                  new SelectListItem { Text = "2013", Value = "2013" },
                  new SelectListItem { Text = "2014", Value = "2013" },
                  new SelectListItem { Text = "2015", Value = "2015" },
                  new SelectListItem { Text = "2016", Value = "2016" },
                  new SelectListItem { Text = "2017", Value = "2017" },
                  new SelectListItem { Text = "2018", Value = "2018" },
                  new SelectListItem { Text = "2019", Value = "2019" },
                  new SelectListItem { Text = "2020", Value = "2020" },
                  }, new { @class = "form-control input-xs select-search", @validationTabDetails = "validation" })
                        <span class="focus-input"></span>
                    </div>
                    <div class="form-group mt-10">
                        <label>Email</label>&nbsp;<span style="color:red">*</span>
                        @Html.TextBoxFor(a => a.email, new { @class = "form-control", @placeholder = "enter email", @validationTabDetails = "validation" })
                        <span class="focus-input"></span>
                    </div>
                    <div class="form-group mt-10">
                        <label>Password</label>&nbsp;<span style="color:red">*</span>
                        @Html.PasswordFor(a => a.password, new { @class = "form-control", @placeholder = "*****************", @validationTabDetails = "validation" })
                        <span class="focus-input"></span>
                    </div>
                    <div class="form-group mt-10 pull-right">
                        <input type="button" id="btnRegister" onclick="alumni_registraion('register');" value="Click To Register" class="btn btn-primary" />
                    </div>
                </div>
            </div>
            @*<div class="form-group mt-10">
                    <label>Contact No.</label>&nbsp;<span style="color:red">*</span>
                    @Html.TextBoxFor(a => a.contact_number, new { @class = "form-control", @placeholder = "enter contact no.", @validationTabDetails = "validation" })
                    <span class="focus-input"></span>
                </div>
                <div class="form-group mt-10">
                    <label>Email</label>&nbsp;<span style="color:red">*</span>
                    @Html.TextBoxFor(a => a.email, new { @class = "form-control", @placeholder = "enter email", @validationTabDetails = "validation" })
                    <span class="focus-input"></span>
                </div>
                <div class="form-group mt-10">
                    <label>Password</label>&nbsp;<span style="color:red">*</span>
                    @Html.PasswordFor(a => a.password, new { @class = "form-control", @placeholder = "*****************", @validationTabDetails = "validation" })
                    <span class="focus-input"></span>
                </div>
                <div class="form-group mt-10 pull-right">
                    <input type="button" id="btnRegister" onclick="alumni_registraion('register');" value="Click To Register" class="btn btn-primary" />
                </div>*@

        </div>
    </div>
</div>

@*<%--Ok Or cancel modal popup for deleteing the record--%>*@
<div id="message" class="modal fade bs-example-modal-sm in" tabindex="-1" role="dialog" aria-labelledby="ConfirmationEmailModal" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content c-square">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="mySmallModalLabel"></h4>
            </div>
            <div class="modal-body">
                <span id="alert_message"></span>
                @* <b>Thank You!</b> Registration is successful. Kindly check the registerd email account to verify.*@
                <div class="row">
                    <div class="col-sm-12">
                        <div class="btn-group pull-right">
                            <button type="button" class="btn btn-primary c-theme-btn c-btn-border-2x c-btn-square c-btn-bold c-btn-uppercase" data-dismiss="modal" onclick="refreshPage();">OK</button>
                        </div>
                        <div class="btn-group pull-right mr-5">
                            <button type="button" class="btn btn-info button-next" data-dismiss="modal">Cancel</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
@*</form>*@


<!-- start js include path -->
<script src="../content/js/login.js"></script>
<script src="../content/js/pages.js" type="text/javascript"></script>
<script src="~/Scripts/Batchmates/03_alumni_registration.js"></script>
<script src="~/Scripts/Batchmates/02_page_validations.js"></script>
<!-- end js include path -->

Alumini/Views/authentication/users.cshtml
@{
    ViewBag.Title = "users";
}

<h2>users</h2>

Alumini/Views/authentication/verifyaccount.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>verifyaccount</title>
</head>
<body>
    <div style="margin-top:50px;">
        <div style="text-align:center;font-family:Arial, Helvetica, sans-serif; font-size:17px;color:#c71585;" id="verificationMessage"></div><br />

        <div style="text-align:center;font-family:Arial, Helvetica, sans-serif;text-decoration:none; font-size:15px;">
            <a href="~/authentication/login" style="padding:8px 12px;border:1px solid #c71585;border-radius:2px;font-family:Helvetica, Arial, sans-serif;font-size:16px;background-color:#c71585;color:#fff;text-decoration:none;font-weight:bold;display:inline-block;">Go to Login</a>
        </div>
    </div>
</body>
</html>
<script src="~/assets/js/core/jquery.min.js" type="text/javascript"></script>
<script src="~/assets/js/jquery-ui.min.js" type="text/javascript"></script>
<script src="~/Scripts/Batchmates/03_alumni_registration.js"></script>